### ISSUE TITLE
在Gateway服务中，跳过验证的那个地址，在路由转发中怎么写？

### ISSUE THREAD

**Issue by EGo14T** [steventong/simple-microservices#2]
.pathMatchers("/actuator/**").permitAll()；
我试了请求/actuator 转发到其他地址，这个地址也需要验证
那么这个permitAll地址应该写才能起作用呢？就是不需要验证

**Comment by steventong** [comment]
有点时间没看了，如果是访问 gateway 的 actuator，配置一下 web security ( 或者 resource server configurer ? ) 应该就是可以了，如果是通过 gateway 访问比如 api server 的 actuator，还得把 api server 在 gateway 中的 route 配置进去，类似于 `/api/actuator/**`

我晚点实现一下这个。

**Comment by EGo14T** [comment]
嗯嗯，我已经实现了，谢谢您的回复^_^
