### ISSUE TITLE
返回用户名信息

### ISSUE THREAD

**Issue by poer44** [steventong/simple-microservices#3]
怎么在api-server中用jwt去返回他的用户名等信息呢

**Comment by steventong** [comment]
我近期更新一下，把这个功能实现一下。

**Comment by steventong** [comment]
b24119c8daead1ba7dea2623e23c2c337afca329

简单实现了一下，通过 @AuthenticationPrincipal 可以拿到，如果要返回具体的完整的用户对象，需要实现一个 user converter
