### ISSUE TITLE
如何通过网关获得Token？

### ISSUE THREAD

**Issue by zhoulin00** [steventong/simple-microservices#4]
需要先通过8081请求授权服务器获得token，然后再将请求带上token请求网关8082。
怎么统一使用网关获得token啊？需要用gateway的Filter去操作吗？

**Comment by steventong** [comment]
最简单的思路，加一段 uri route 呗，将 auth-service 也通过 gateway 代理。这样所有的服务对外都是通过 gateway 提供服务。
